In [6]:
import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = h5py.File('data/new.HDF', 'w')

In [7]:
d250 = h5py.File('data/Y3E_08534_230226070855_7860R_MERSI_0250M_L1B.HDF', 'r')
d250.keys()

<KeysViewHDF5 ['Calibration', 'Data', 'Geolocation', 'QA']>

In [9]:
list(d250['Data']['EV_250_Emissive_b6'])

[array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([1433, 1433, 1433, ...,    0,    0,    0], dtype=uint16),
 array([9596, 9562, 9613, ...,    0,    0,    0], dtype=uint16),
 array([9483, 9500, 9512, ...,    0,    0,    0], dtype=uint16),
 array([9286, 9495, 9562,

In [8]:
d250.copy(d250['Calibration'], data['/'], 'Calibration')

In [15]:
geo = h5py.File('data/Y3E_08534_230226070855_7860R_MERSI_GEOQK_L1B.HDF', 'r')
geo.keys()

<KeysViewHDF5 ['Altitude', 'DayNightFlag', 'Day_Count', 'Latitude', 'Longitude', 'Millisecond_Count', 'QA_index', 'SensorAzimuth', 'SensorZenith', 'SolarAzimuth', 'SolarZenith']>

In [16]:
geo.copy(geo['Latitude'], data['/'], 'Latitude')
geo.copy(geo['Longitude'], data['/'], 'Longitude')

In [17]:
data.close()

In [18]:
geo['Longitude']

<HDF5 dataset "Longitude": shape (20000, 6144), type "<f4">